### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by maryisdead** [10up/eight-day-week#11]
Attached is a German translation containing both _.po_ and _.mo_. I translated to my best knowledge (am a webdev working in an agency heavily focused on print media). There are some interface strings that the plug-in didn't seem to include a translation mechanism for (see 
screenshot below). I didn't bother with them for now.

![screen shot 2016-06-10 at 09 24 05](https://cloud.githubusercontent.com/assets/14194/15957109/3859c11c-2eed-11e6-9f18-1247b6487b08.png)

Sorry for not making a proper PR, no time!

[eight-day-week-de_DE.zip](https://github.com/observermedia/eight-day-week/files/308522/eight-day-week-de_DE.zip)

**Comment by jeffpaul** [comment]
Assuming the files in the attached ZIP still apply, we could look to bundle this with v1.1.0.

**Comment by adamsilverstein** [comment]
Hi @maryisdead thanks for the translation! This seems like a useful contribution and highlights some strings that aren't currently translatable.

@jeffpaul I can open a PR to include the .mo file (the .po is not required afaik). I can't review the translations myself - maybe worth asking a German speaker on the team to do a quick review? 

Dropping some screenshots here where this can be reviewed and where we can spot non-translated strings (I think mainly 'Issue Date' and 'Save'):

![image](https://user-images.githubusercontent.com/2676022/61897829-285d9700-aed5-11e9-840b-d9658ef12af8.png)

![image](https://user-images.githubusercontent.com/2676022/61897838-314e6880-aed5-11e9-8755-d5179227c995.png)

![image](https://user-images.githubusercontent.com/2676022/61897848-390e0d00-aed5-11e9-8f42-1aa6c262ee75.png)

![image](https://user-images.githubusercontent.com/2676022/61897857-40351b00-aed5-11e9-9af1-e40f3fe4f69e.png)

**Comment by adamsilverstein** [comment]
Resolved in https://github.com/10up/eight-day-week/pull/31
