### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by jeffpaul** [10up/eight-day-week#26]
**Is your enhancement related to a problem? Please describe.**
In order to automate our WordPress.ORG deploys, let's leverage the GitHub Actions that @helen built.

**Describe the solution you'd like**
Setup the GitHub Actions to handle `dotorg-plugin-asset-update` and `dotorg-plugin-deploy` from https://github.com/10up/actions-wordpress.

**Designs**
n/a

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by helen** [comment]
Fixed in #35
