### ISSUE TITLE
Add develop branch

### ISSUE THREAD

**Issue by jeffpaul** [10up/eight-day-week#27]
**Is your enhancement related to a problem? Please describe.**
Add a `develop` branch and set as default, to mimic 10up repo standards.

**Describe the solution you'd like**
See above.

**Designs**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by adamsilverstein** [comment]
* Added develop branch
* Set develop to default branch
* Added branch protection rules for master and develop (note: no checks yet in this repo)

Closing as resolved.
