### ISSUE TITLE
Allow Print CPT to function within Gutenberg

### ISSUE THREAD

**Issue by jeffpaul** [10up/eight-day-week#29]
**Is your enhancement related to a problem? Please describe.**
As @adamsilverstein noted in #28:

> Test Gutenberg compatibility: no changes are made to the post editor with this plugin so far. The "Print" custom post type added by the plugin opens in the classic edit environment because `show_in_rest` is not set (Gutenberg requires REST API access to use a CPT). Everything works as expected in my testing.

We'll want to build in support for Gutenberg-based editing in the Print CPT so that publishers who have converted to using Gutenberg for editing can utilize Eight Day Week.

**Describe the solution you'd like**
- [ ] set `show_in_rest` to true for the `Print` CPT
- [ ] test Gutenberg-based Print output exports correctly for InDesign
- [ ] handle any inconsistencies in the Gutenberg-based output for the InDesign export

**Designs**
n/a

**Describe alternatives you've considered**
none.

**Additional context**
Child issue of #19, related to #28.

**Comment by adamsilverstein** [comment]
Maybe we can start by exploring some ideas/sketches of what this might look like in Gutenberg.

**Comment by jeffpaul** [comment]
I'm not certain there's a benefit to making this change, so closing out this issue.  Happy to re-open if someone has a different take that would make this relevant.
