### ISSUE TITLE
DateTimeZone Error

### ISSUE THREAD

**Issue by Jared-Williams** [10up/eight-day-week#5]
I was testing out this plugin for a client and got an error when trying to export.

```
{"success":false,"data":{"message":"DateTimeZone::__construct(): Unknown or bad timezone ()","_ajax_nonce":"6a4ac07ddc"}}
```

I replaced this:

```
/**
 * Builds the file name for the zip
 * Uses the print issue title & day/time
 *
 * @uses get_timezone
 *
 * @return string The zip file name
 */
function get_zip_file_name( ) {
    $date = new \DateTime( 'now', new \DateTimeZone( get_option( 'timezone_string' ) ) );
    return 'Issue ' . $this->issue_title . ' exported on ' . $date->format( 'm-d-y' ) . ' at ' . $date->format( 'h:ia' );
}
```

with your previous version:

```
/**
 * Builds the file name for the zip
 * Uses the print issue title & day/time
 *
 * @uses get_timezone
 *
 * @return string The zip file name
 */
function get_zip_file_name( ) {
    date_default_timezone_set( Core\get_timezone() );
    return sprintf( __( 'Issue %1$s exported on %2$s at %3$s', 'eight-day-week' ), $this->issue_title, date( 'm-d-y' ), date( 'h:ia' ) );
}
```

And the error went away and I could save the Export file. Not sure if you are seeing this on your end, but wanted to let you know.

**Comment by sternb0t** [comment]
Thanks for the note @Jared-Williams. This is actually an issue that we ran into with our hosting provider (on WordPress.com). I'll let @joshlevinson comment on this further, but we're actually in the process of deploying the newer version on Observer.com since WP.com doesn't want us using `date_default_timezone_set()`. 

However this may be something we want to test for and provide a fallback with UTC or something like that?

**Comment by joshlevinson** [comment]
Hi, @Jared-Williams! Thanks for the report.
Can you tell me what is set on your WordPress install for the timezone/offset (under Settings -> General)? I'm assuming it may be a GMT offset, which wasn't previously accounted for. It is now in #8.

**Comment by Jared-Williams** [comment]
Yea sure, it's UTC-6. I can revert and see if that works on my end.

**Comment by joshlevinson** [comment]
@Jared-Williams No worries, I'd like to know this works in your setup, not have your setup bow to the current implementation of this plugin :-)
Can you confirm that the latest master (as of #8 being merged) fixes your issue with your offset being -6?
Thanks!

**Comment by Jared-Williams** [comment]
Hey @joshlevinson sorry for the delay in getting back with you. I updated to the latest version of the plugin and the error returns upon export

    {"success":false,"data":{"message":"DateTimeZone::__construct(): Unknown or bad timezone ()","_ajax_nonce":"d07eec4ba8"}}

When I changed it to say, "Chicago", it works fine. I can easily just keep it at Chicago instead of GMT offset.

**Comment by adamsilverstein** [comment]
@Jared-Williams I pushed a fix for this issue in https://github.com/10up/eight-day-week/pull/32 - if you have a chance, can you give it a test?
